fix: retry to fix entry file
```log
➜  redwood.XXXXXX.hlo6ZiKR git:(main) yarn rw dev --no-generate --fwd="--no-open"
api | Building... Took 312 ms
api | Debugger listening on ws://127.0.0.1:18911/7da253a8-3807-4517-bcb2-d593fd9b5f41
api | For help, see: https://nodejs.org/en/docs/inspector
web | [webpack-cli] Failed to load '/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/@redwoodjs/core/config/webpack.development.js' config
web | [webpack-cli] Error: Cannot find module '@redwoodjs/web/dist/entry/index.js'
web | Require stack:
web | - /private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/@redwoodjs/core/config/webpack.common.js
web | - /private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/@redwoodjs/core/config/webpack.development.js
web | - /private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/webpack-cli/lib/webpack-cli.js
web | - /private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/webpack-cli/lib/bootstrap.js
web | - /private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/webpack-cli/bin/cli.js
web | - /private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/webpack/bin/webpack.js
web | - /private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/webpack/package.json
web |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
web |     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
web |     at module.exports (/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/@redwoodjs/core/config/webpack.common.js:210:17)
web |     at Object.<anonymous> (/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/@redwoodjs/core/config/webpack.development.js:84:26)
web |     at Module._compile (node:internal/modules/cjs/loader:1126:14)
web |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
web |     at Module.load (node:internal/modules/cjs/loader:1004:32)
web |     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
web |     at Module.require (node:internal/modules/cjs/loader:1028:19)
web |     at require (node:internal/modules/cjs/helpers:102:18) {
web |   code: 'MODULE_NOT_FOUND',
web |   requireStack: [
web |     '/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/@redwoodjs/core/config/webpack.common.js',
web |     '/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/@redwoodjs/core/config/webpack.development.js',
web |     '/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/webpack-cli/lib/webpack-cli.js',
web |     '/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/webpack-cli/lib/bootstrap.js',
web |     '/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/webpack-cli/bin/cli.js',
web |     '/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/webpack/bin/webpack.js',
web |     '/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/webpack/package.json'
web |   ]
web | }
web | cd "/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/web" && yarn cross-env NODE_ENV=development RWJS_WATCH_NODE_MODULES= webpack serve --config "/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/node_modules/@redwoodjs/core/config/webpack.development.js" --no-open exited with code 1
api | Starting API Server...
api | Loading server config from /private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/api/server.config.js
api |
api | 20:49:53 🌲 Configuring api side
api | 🗒 Custom
api | {
api |   "options": {
api |     "side": "api",
api |     "_": [
api |       "api"
api |     ],
api |     "port": 8911,
api |     "p": 8911,
api |     "apiRootPath": "/",
api |     "rootPath": "/",
api |     "root-path": "/",
api |     "api-root-path": "/",
api |     "$0": "node_modules/@redwoodjs/api-server/dist/index.js"
api |   }
api | }
api | Importing Server Functions...
api | /graphql 506 ms
api | ...Done importing in 507 ms
api | Took 558 ms
api | API listening on http://localhost:8911/
api | GraphQL endpoint at /graphql
api | 20:49:54 🐛 Fastify server configuration
api | 🗒 Custom
api | {
api |   "requestTimeout": 15000,
api |   "connectionTimeout": 0,
api |   "keepAliveTimeout": 72000,
api |   "maxRequestsPerSocket": 0,
api |   "requestIdHeader": "request-id",
api |   "requestIdLogLabel": "reqId",
api |   "disableRequestLogging": false,
api |   "bodyLimit": 1048576,
api |   "caseSensitive": true,
api |   "allowUnsafeRegex": false,
api |   "ignoreTrailingSlash": false,
api |   "ignoreDuplicateSlashes": false,
api |   "jsonShorthand": true,
api |   "maxParamLength": 100,
api |   "onProtoPoisoning": "error",
api |   "onConstructorPoisoning": "error",
api |   "pluginTimeout": 10000,
api |   "http2SessionTimeout": 72000,
api |   "exposeHeadRoutes": true
api | }
api | 20:49:54 🐛 Registered plugins
api | bound root 544 ms
api | ├── bound _after 4 ms
api | ├── @fastify/url-data 0 ms
api | ├── fastify-raw-body 0 ms
api | ├── bound _after 0 ms
api | ├── bound _after 0 ms
api | ├── bound _after 0 ms
api | ├── bound _after 1 ms
api | └── bound _after 0 ms
api |
api | 20:49:54 🌲 Server listening at http://[::]:8911
 ^Capi | yarn cross-env NODE_ENV=development NODE_OPTIONS=--enable-source-maps yarn nodemon --quiet --watch "/private/var/folders/zr/gnbk06q10kdg8jvj1mqd944m0000gn/T/redwood.XXXXXX.hlo6ZiKR/redwood.toml" --exec "yarn rw-api-server-watch --debug-port 18911 | rw-log-formatter" exited with code SIGINT
```